// Generated by CoffeeScript 1.3.3
var datas, fetch, fs, marge, read, url_list, write,
  _this = this;

fetch = function(req_url, callback) {
  var $, client, http, parsed_url, request, url,
    _this = this;
  http = require("http");
  url = require("url");
  $ = require("jquery");
  parsed_url = url.parse(req_url);
  client = http.createClient(80, parsed_url.hostname);
  request = client.request('GET', parsed_url.pathname, {
    'host': parsed_url.hostname
  });
  request.end();
  return request.on('response', function(response) {
    var html;
    response.setEncoding("utf-8");
    html = "";
    response.on('data', function(data) {
      return html += data;
    });
    return response.on('end', function() {
      var result, _ref, _ref1;
      console.log("end " + req_url);
      result = {};
      result.url = req_url;
      result.owner = $(html).find("#community_prof_frm2 .r p:last-child strong").text();
      result.level = $(html).find("#cbox_profile table table tr:first-child td:nth-child(2) strong:first-child").text();
      result.members = $(html).find("#cbox_profile table table tr:nth-child(2) td:nth-child(2) strong:first-child").text();
      result.totals = $(html).find("#cbox_profile table table tr:nth-child(6) td:nth-child(2) strong:first-child").text();
      result.prof_bonus = ((_ref = $(html).find("#community_description .subbox .cnt2").text().match(/風来|シレン|TM|フェイ/g)) != null ? _ref.length : void 0) || 0;
      result.news_bonus = ((_ref1 = $(html).find("#news .cnt2").text().match(/風来|シレン|フェイ|TM/g)) != null ? _ref1.length : void 0) || 0;
      return callback(result);
    });
  });
};

marge = function(obj) {
  datas.results.push(obj);
  if (datas.results.length === url_list.length) {
    write.write(JSON.stringify(datas));
    return console.log("complete task");
  }
};

datas = {
  results: []
};

fs = require("fs");

read = fs.createReadStream("./entry.txt", {
  encoding: "utf8"
});

write = fs.createWriteStream("../bin/entry.json", {
  encoding: "utf8"
});

url_list = null;

read.on("data", function(line) {
  return url_list = line.match(/co[0-9]+/g);
}).on("end", function() {
  var req_url, _i, _len, _results;
  _results = [];
  for (_i = 0, _len = url_list.length; _i < _len; _i++) {
    req_url = url_list[_i];
    _results.push(fetch("http://com.nicovideo.jp/community/" + req_url, marge));
  }
  return _results;
});
